# Data Extraction
source("DataExtraction112x_Rushdi.R")
source("DataExtraction121x_Rushdi.R")
source("DataExtraction122x_Rushdi.R")
source("DataExtraction142x_Rushdi.R")
source("DataExtraction152x_Rushdi.R")
source("DataExtraction161x_Rushdi.R")
source("DataExtraction162x_Rushdi.R")
source("DataExtraction171x_Rushdi.R")
source("DataExtraction172x_Rushdi.R")
source("DataExtraction182x_Rushdi.R")
source("DataExtraction191x_Rushdi.R")
source("DataExtraction192x_Rushdi.R")

# Speed smoothing

source("SmoothSpeed_112x.R")
source("SmoothSpeed_121x.R")
source("SmoothSpeed_122x.R")
source("SmoothSpeed_142x.R")
source("SmoothSpeed_152x.R")
source("SmoothSpeed_161x.R")
source("SmoothSpeed_162x.R")
source("SmoothSpeed_171x.R")
source("SmoothSpeed_172x.R")
source("SmoothSpeed_182x.R")
source("SmoothSpeed_191x.R")
source("SmoothSpeed_192x.R")

# Yaw Angle
source("yawAngle_112x.R")
source("yawAngle_121x.R")
source("yawAngle_122x.R")
source("yawAngle_142x.R")
source("yawAngle_152x.R")
source("yawAngle_161x.R")
source("yawAngle_162x.R")
source("yawAngle_171x.R")
source("yawAngle_172x.R")
source("yawAngle_182x.R")
source("yawAngle_191x.R")
source("yawAngle_192x.R")

#Variable Calculation
source("Variable_Calc_112x.R")
source("Variable_Calc_121x.R")
source("Variable_Calc_122x.R")
source("Variable_Calc_142x.R")
source("Variable_Calc_152x.R")
source("Variable_Calc_161x.R")
source("Variable_Calc_162x.R")
source("Variable_Calc_171x.R")
source("Variable_Calc_172x.R")
source("Variable_Calc_182x.R")
source("Variable_Calc_191x.R")
source("Variable_Calc_192x.R")